[[language]]
name = "c"
language-servers = []

[[language]]
name = "cpp"
language-servers = []

[[language]]
name = "rust"
language-servers = []

[[language]]
name = "python"
language-servers = []

[[language]]
name = "javascript"
language-servers = []
