[[language]]
name = "c"
language-server = { command = "" }

[[language]]
name = "cpp"
language-server = { command = "" }

[[language]]
name = "rust"
language-server = { command = "" }

[[language]]
name = "python"
language-server = { command = "" }

[[language]]
name = "javascript"
language-server = { command = "" }