[[language]]
name = "c"
# language-servers = []
language-servers = [{ name = "clangd", except-features = [ "diagnostics" ] }]

[[language]]
name = "cpp"
# language-servers = []
language-servers = [{ name = "clangd", except-features = [ "diagnostics" ] }]

[[language]]
name = "rust"
language-servers = []

[[language]]
name = "python"
language-servers = []

[[language]]
name = "javascript"
language-servers = []
